### ISSUE TITLE
Update jsDoc so that we can run demos:serve in node 8

### ISSUE THREAD

**Issue by sound-matt** [eventbrite/britecharts#492] opened 2018-01-26 15:41 UTC
I don't if I missing a step but I can't run `yarn demos:serve` 

## Expected Behavior

Following the step described in CONTRIBUTING.md `yarn demos:serve` should serve the demo

## Current Behavior

When running `yarn docs` I have an error
```
Running "jsdoc:dist" (jsdoc) task
>> fs.js:1919
>>   binding.copyFile(src, dest, flags);
>>           ^
>>
>> Error: EISDIR: illegal operation on a directory, copyfile '/home/matt/DEV_PROJECTS/TestAndForget/britecharts/src/doc/html/cdn-iframe.html' -> '/home/matt/DEV_PROJECTS/TestAndForget/britecharts/docs'
>>     at Object.fs.copyFileSync (fs.js:1919:11)
>>     at /home/matt/DEV_PROJECTS/TestAndForget/britecharts/src/doc/template/publish.js:642:20
>>     at Array.forEach (<anonymous>)
>>     at /home/matt/DEV_PROJECTS/TestAndForget/britecharts/src/doc/template/publish.js:638:30
>>     at Array.forEach (<anonymous>)
>>     at Object.exports.publish (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/src/doc/template/publish.js:635:25)
>>     at Object.module.exports.cli.generateDocs (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/cli.js:448:35)
>>     at Object.module.exports.cli.processParseResults (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/cli.js:399:20)
>>     at module.exports.cli.main (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/cli.js:240:14)
>>     at Object.module.exports.cli.runCommand (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/cli.js:189:5)
>>     at /home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/jsdoc.js:105:9
>>     at Object.<anonymous> (/home/matt/DEV_PROJECTS/TestAndForget/britecharts/node_modules/jsdoc/jsdoc.js:106:3)
>>     at Module._compile (module.js:624:30)
>>     at Object.Module._extensions..js (module.js:635:10)
>>     at Module.load (module.js:545:32)
>>     at tryModuleLoad (module.js:508:12)
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So docs directory is not built correctly even if I do `yarn run docs --force`

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:eventbrite/britecharts.git`
2. `yarn install`
3. `yarn docs`
4. `yarn demos:serve`

## Your Environment

* Version used: 2.4.11
* Browser Name and version:
* Operating System and version (desktop or mobile): Linux ubuntu
* Yarn: 1.3.2
* Node: 8.6.0
* Link to your project:

**Comment by Golodhros** [comment] 2018-01-27 00:20
Hi @sound-matt, thanks for opening an issue!

I tried to reproduce it with no luck.

It looks like a permissions issue. Sometimes these get resolved by simply running `rm -rf node_modules` and `yarn` afterward.

Let me know if that worked!

**Comment by sound-matt** [comment] 2018-01-27 11:06
I retried on an other computer, that time I had no errors with the commands `yarn docs` and `yarn demos:serve` but when I go to localhost:8001 there no templates, I have only see the content of "docs" directory (font/, scripts/, styles/, manifest.json). 

Is there an other command to run ?

**Comment by Golodhros** [comment] 2018-01-27 16:20
Weird...
Usually I would have a terminal running `yarn demos:serve` and in a different one run `yarn docs`

**Comment by dalerasrorov-eb** [comment] 2018-01-28 07:27
@sound-matt can you try running with `npm` instead? If that doesn't work trying with `npm run docs` first.

**Comment by sound-matt** [comment] 2018-01-28 21:35
I made a few tests and I found what the problem was. I think I had 2 different problems. When I made my seconds test I did on a window 10 using "bash for windows" as my terminal, after some research I discovered that when I do `npm install` (or `yarn install`) in the terminal "bash for windows" the directory `node_modules/.bin` is not filled with all the binaries, so the grunt task `jsdoc:dist` doesn't works. 
So in normal condition on windows, it works :)
And I remade the test with an ubuntu its works too, maybe it was some permision issue as you said

**Comment by sound-matt** [comment] 2018-02-02 16:13
Finaly, the problem was a real thing
https://github.com/krampstudio/grunt-jsdoc/issues/179

`yarn upgrade` fix the issue with my version of node

**Comment by dalerasrorov-eb** [comment] 2018-02-02 18:36
@sound-matt I had same issue multiple times

**Comment by Golodhros** [comment] 2018-02-02 20:28
Which node version are you guys using?
In theory we are still in 6.9.2

**Comment by sound-matt** [comment] 2018-02-05 08:50
I use node last LTS (8.9.4). The problem with the command `yarn docs` is due to jsdoc, before the version 3.5.5 it isn't compatible with node 8.5.0 (and higher), so I upgrade `grunt-jsdoc` and it works fine

**Comment by Golodhros** [comment] 2018-02-06 01:26
Awesome, thanks!

**Closed** 2018-02-08 18:18 UTC
Labels: build, enhancement, help wanted
